name: CouponCodes
main: net.lala.CouponCodes.CouponCodes
version: 2.1.0
author: mike101102, eMpTy
softdepend: [Vault]
commands:
    c:
        aliases: [coupon]
        description: CouponCode's main command
        usage: /<command>
permissions:
    cc.*:
        description: Gives access to all coupon commands
        children:
            cc.add: true
            cc.redeem: true
            cc.remove: true
            cc.list: true
            cc.reload: true
            cc.info: true
            cc.update: true
    cc.add:
        description: Allows you to add a coupon
        default: false
    cc.redeem:
        description: Allows you to redeem a coupon
        default: false
    cc.remove:
        description: Allows you to remove a coupon
        default: false
    cc.list:
        description: Allows you to see a list of all the coupons
        default: false
    cc.info:
        description: Allows you to view information on coupons
        default: false
    cc.update:
        description: Notifies you when there is an update
        default: false
    cc.reload:
        description: Allows you to reload the database
        default: false